<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('inventarios', function (Blueprint $table) {
            $table->id();
            $table->string('programa')->require();
            $table->string('director_programa')->require();
            $table->string('telefono_director')->require();
            $table->string('correo')->require();
            $table->string('nombre_encargado')->require();
            $table->string('telefono_encargado')->require();
            $table->integer('sillas_cantidades')->nullable();
            $table->integer('sillas_prestar')->nullable();
            $table->integer('sillas_reparar')->nullable();
            $table->integer('mesas_oficina_cantidades')->nullable();
            $table->integer('mesas_oficina_prestar')->nullable();
            $table->integer('mesas_oficina_reparar')->nullable();
            $table->integer('telas_decoracion_cantidades')->nullable();
            $table->integer('telas_decoracion_prestar')->nullable();
            $table->integer('telas_decoracion_reparar')->nullable();
            $table->integer('afiches_pendones_cantidades')->nullable();
            $table->integer('afiches_pendones_prestar')->nullable();
            $table->integer('afiches_pendones_reparar')->nullable();
            $table->integer('cuadros_cantidades')->nullable();
            $table->integer('cuadros_prestar')->nullable();
            $table->integer('cuadros_reparar')->nullable();
            $table->integer('bandera_interior_cantidades')->nullable();
            $table->integer('bandera_interior_prestar')->nullable();
            $table->integer('bandera_interior_reparar')->nullable();
            $table->integer('bandera_exterior_cantidades')->nullable();
            $table->integer('bandera_exterior_prestar')->nullable();
            $table->integer('bandera_exterior_reparar')->nullable();
            $table->integer('astas_bandera_cantidades')->nullable();
            $table->integer('astas_bandera_prestar')->nullable();
            $table->integer('astas_bandera_reparar')->nullable();
            $table->integer('decoracion_cantidades')->nullable();
            $table->integer('decoracion_prestar')->nullable();
            $table->integer('decoracion_reparar')->nullable();
            $table->integer('termos_agua_cantidades')->nullable();
            $table->integer('termos_agua_prestar')->nullable();
            $table->integer('termos_agua_reparar')->nullable();
            $table->integer('termos_cafe_cantidades')->nullable();
            $table->integer('termos_cafe_prestar')->nullable();
            $table->integer('termos_cafe_reparar')->nullable();
            $table->integer('cafeteras_cantidades')->nullable();
            $table->integer('cafeteras_prestar')->nullable();
            $table->integer('cafeteras_reparar')->nullable();
            $table->integer('microondas_cantidades')->nullable();
            $table->integer('microondas_prestar')->nullable();
            $table->integer('microondas_reparar')->nullable();
            $table->integer('cocinas_cantidades')->nullable();
            $table->integer('cocinas_prestar')->nullable();
            $table->integer('cocinas_reparar')->nullable();
            $table->integer('platos_sopa_cantidades')->nullable();
            $table->integer('platos_sopa_prestar')->nullable();
            $table->integer('platos_sopa_reparar')->nullable();
            $table->integer('ollas_sopa_cantidades')->nullable();
            $table->integer('ollas_sopa_prestar')->nullable();
            $table->integer('ollas_sopa_reparar')->nullable();
            $table->integer('calderos_cantidades')->nullable();
            $table->integer('calderos_prestar')->nullable();
            $table->integer('calderos_reparar')->nullable();
            $table->integer('cucharillas_cantidades')->nullable();
            $table->integer('cucharillas_prestar')->nullable();
            $table->integer('cucharillas_reparar')->nullable();
            $table->integer('tenedores_cantidades')->nullable();
            $table->integer('tenedores_prestar')->nullable();
            $table->integer('tenedores_reparar')->nullable();
            $table->integer('vasos_cantidades')->nullable();
            $table->integer('vasos_prestar')->nullable();
            $table->integer('vasos_reparar')->nullable();
            $table->integer('sonido_cantidades')->nullable();
            $table->integer('sonido_prestar')->nullable();
            $table->integer('sonido_reparar')->nullable();
            $table->integer('cornetas_cantidades')->nullable();
            $table->integer('cornetas_prestar')->nullable();
            $table->integer('cornetas_reparar')->nullable();
            $table->integer('microfonos_cable_cantidades')->nullable();
            $table->integer('microfonos_cable_prestar')->nullable();
            $table->integer('microfonos_cable_reparar')->nullable();
            $table->integer('microfonos_inalambricos_cantidades')->nullable();
            $table->integer('microfonos_inalambricos_prestar')->nullable();
            $table->integer('microfonos_inalambricos_reparar')->nullable();
            $table->integer('parales_microfonos_cantidades')->nullable();
            $table->integer('parales_microfonos_prestar')->nullable();
            $table->integer('parales_microfonos_reparar')->nullable();
            $table->integer('consola_audio_cantidades')->nullable();
            $table->integer('consola_audio_prestar')->nullable();
            $table->integer('consola_audio_reparar')->nullable();
            $table->integer('plantas_audio_cantidades')->nullable();
            $table->integer('plantas_audio_prestar')->nullable();
            $table->integer('plantas_audio_reparar')->nullable();
            $table->integer('tv_plasma_cantidades')->nullable();
            $table->integer('tv_plasma_prestar')->nullable();
            $table->integer('tv_plasma_reparar')->nullable();
            $table->integer('planta_electrica_cantidades')->nullable();
            $table->integer('planta_electrica_prestar')->nullable();
            $table->integer('planta_electrica_reparar')->nullable();
            $table->integer('extenciones_electricas_cantidades')->nullable();
            $table->integer('extenciones_electricas_prestar')->nullable();
            $table->integer('extenciones_electricas_reparar')->nullable();
            $table->integer('cables_microfonos_cantidades')->nullable();
            $table->integer('cables_microfonos_prestar')->nullable();
            $table->integer('cables_microfonos_reparar')->nullable();
            $table->integer('video_beam_cantidades')->nullable();
            $table->integer('video_beam_prestar')->nullable();
            $table->integer('video_beam_reparar')->nullable();
            $table->integer('almohadillas_cantidades')->nullable();
            $table->integer('almohadillas_prestar')->nullable();
            $table->integer('almohadillas_reparar')->nullable();
            $table->integer('condecoraciones_fisicas_cantidades')->nullable();
            $table->integer('condecoraciones_fisicas_prestar')->nullable();
            $table->integer('condecoraciones_fisicas_reparar')->nullable();
            $table->integer('automovil_cantidades')->nullable();
            $table->integer('automovil_prestar')->nullable();
            $table->integer('automovil_reparar')->nullable();
            $table->integer('camara_fotografica_cantidades')->nullable();
            $table->integer('camara_fotografica_prestar')->nullable();
            $table->integer('camara_fotografica_reparar')->nullable();
            $table->integer('camara_grabacion_cantidades')->nullable();
            $table->integer('camara_grabacion_prestar')->nullable();
            $table->integer('camara_grabacion_reparar')->nullable();
            $table->integer('personal_publicas_cantidades')->nullable();
            $table->integer('personal_publicas_prestar')->nullable();
            $table->integer('personal_publicas_reparar')->nullable();
            $table->integer('carpetas_firmas_cantidades')->nullable();
            $table->integer('carpetas_firmas_prestar')->nullable();
            $table->integer('carpetas_firmas_reparar')->nullable();
            $table->integer('personal_idiomas_cantidades')->nullable();
            $table->integer('personal_idiomas_prestar')->nullable();
            $table->integer('personal_idiomas_reparar')->nullable();
            $table->string('personal_idiomas_tipo')->nullable();
            $table->integer('personal_sennas_cantidades')->nullable();
            $table->integer('personal_sennas_prestar')->nullable();
            $table->integer('personal_sennas_reparar')->nullable();
            $table->integer('personal_culturales_cantidades')->nullable();
            $table->integer('personal_culturales_prestar')->nullable();
            $table->integer('personal_culturales_reparar')->nullable();
            $table->integer('personal_carruchas_cantidades')->nullable();
            $table->integer('personal_carruchas_prestar')->nullable();
            $table->integer('personal_carruchas_reparar')->nullable();
            $table->integer('personal_manteleria_cantidades')->nullable();
            $table->integer('personal_manteleria_prestar')->nullable();
            $table->integer('personal_manteleria_reparar')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('inventarios');
    }
};
