<?php

namespace App\Http\Controllers;

use App\Models\Inventario;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Http\Request;
use Inertia\Inertia;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;

    public function formulario(Request $request)
    {
        $inventario = new Inventario;
        $inventario->programa = $request->input('direccion');
        $inventario->director_programa = $request->input('director');
        $inventario->telefono_director = $request->input('telefonoDirector');
        $inventario->correo = $request->input('correoDirector');
        $inventario->nombre_encargado = $request->input('nombreEncargado');
        $inventario->telefono_encargado = $request->input('telefonoEncargado');
        $inventario->sillas_cantidades = $request->input('silla_oficina_cantidad');
        $inventario->sillas_prestar = $request->input('silla_oficina_activo');
        $inventario->sillas_reparar = $request->input('silla_oficina_inactivo');
        $inventario->mesas_oficina_cantidades = $request->input('mesas_cantidad');
        $inventario->mesas_oficina_prestar = $request->input('mesas_activo');
        $inventario->mesas_oficina_reparar = $request->input('mesas_inactivo');
        $inventario->telas_decoracion_cantidades = $request->input('telas_cantidad');
        $inventario->telas_decoracion_prestar = $request->input('telas_activo');
        $inventario->telas_decoracion_reparar = $request->input('telas_inactivo');
        $inventario->afiches_pendones_cantidades = $request->input('estandartes_cantidad');
        $inventario->afiches_pendones_prestar = $request->input('estandartes_activo');
        $inventario->afiches_pendones_reparar = $request->input('estandartes_inactivo');
        $inventario->cuadros_cantidades = $request->input('cuadros_cantidad');
        $inventario->cuadros_prestar = $request->input('cuadros_activo');
        $inventario->cuadros_reparar = $request->input('cuadros_inactivo');
        $inventario->bandera_interior_cantidades = $request->input('banderas_interior_cantidad');
        $inventario->bandera_interior_prestar = $request->input('banderas_interior_activo');
        $inventario->bandera_interior_reparar = $request->input('banderas_interior_inactivo');
        $inventario->bandera_exterior_cantidades = $request->input('banderas_exterior_cantidad');
        $inventario->bandera_exterior_prestar = $request->input('banderas_exterior_activo');
        $inventario->bandera_exterior_reparar = $request->input('banderas_exterior_inactivo');
        $inventario->astas_bandera_cantidades = $request->input('astas_bandera_cantidad');
        $inventario->astas_bandera_prestar = $request->input('astas_bandera_activo');
        $inventario->astas_bandera_reparar = $request->input('astas_bandera_inactivo');
        $inventario->decoracion_cantidades = $request->input('decoracion_cantidad');
        $inventario->decoracion_prestar = $request->input('decoracion_activo');
        $inventario->decoracion_reparar = $request->input('decoracion_inactivo');
        $inventario->termos_agua_cantidades = $request->input('termos_agua_cantidad');
        $inventario->termos_agua_prestar = $request->input('termos_agua_activo');
        $inventario->termos_agua_reparar = $request->input('termos_agua_inactivo');
        $inventario->termos_cafe_cantidades = $request->input('termos_cafe_cantidad');
        $inventario->termos_cafe_prestar = $request->input('termos_cafe_activo');
        $inventario->termos_cafe_reparar = $request->input('termos_cafe_inactivo');
        $inventario->cafeteras_cantidades = $request->input('cafeteras_cantidad');
        $inventario->cafeteras_prestar = $request->input('cafeteras_activo');
        $inventario->cafeteras_reparar = $request->input('cafeteras_inactivo');
        $inventario->microondas_cantidades = $request->input('microondas_cantidad');
        $inventario->microondas_prestar = $request->input('microondas_activo');
        $inventario->microondas_reparar = $request->input('microondas_inactivo');
        $inventario->cocinas_cantidades = $request->input('cocina_cantidad');
        $inventario->cocinas_prestar = $request->input('cocina_activo');
        $inventario->cocinas_reparar = $request->input('cocina_inactivo');
        $inventario->platos_sopa_cantidades = $request->input('platos_sopa_cantidad');
        $inventario->platos_sopa_prestar = $request->input('platos_sopa_activo');
        $inventario->platos_sopa_reparar = $request->input('platos_sopa_inactivo');
        $inventario->ollas_sopa_cantidades = $request->input('ollas_sopa_cantidad');
        $inventario->ollas_sopa_prestar = $request->input('ollas_sopa_activo');
        $inventario->ollas_sopa_reparar = $request->input('ollas_sopa_inactivo');
        $inventario->calderos_cantidades = $request->input('calderos_cantidad');
        $inventario->calderos_prestar = $request->input('calderos_activo');
        $inventario->calderos_reparar = $request->input('calderos_inactivo');
        $inventario->cucharillas_cantidades = $request->input('cucharas_cantidad');
        $inventario->cucharillas_prestar = $request->input('cucharas_activo');
        $inventario->cucharillas_reparar = $request->input('cucharas_inactivo');
        $inventario->tenedores_cantidades = $request->input('tenedores_cantidad');
        $inventario->tenedores_prestar = $request->input('tenedores_activo');
        $inventario->tenedores_reparar = $request->input('tenedores_inactivo');
        $inventario->vasos_cantidades = $request->input('vasos_cantidad');
        $inventario->vasos_prestar = $request->input('vasos_activo');
        $inventario->vasos_reparar = $request->input('vasos_inactivo');
        $inventario->sonido_cantidades = $request->input('sonido_cantidad');
        $inventario->sonido_prestar = $request->input('sonido_activo');
        $inventario->sonido_reparar = $request->input('sonido_inactivo');
        $inventario->cornetas_cantidades = $request->input('cornetas_cantidad');
        $inventario->cornetas_prestar = $request->input('cornetas_activo');
        $inventario->cornetas_reparar = $request->input('cornetas_inactivo');
        $inventario->microfonos_cable_cantidades = $request->input('microfono_cable_cantidad');
        $inventario->microfonos_cable_prestar = $request->input('microfono_cable_activo');
        $inventario->microfonos_cable_reparar = $request->input('microfono_cable_inactivo');
        $inventario->microfonos_inalambricos_cantidades = $request->input('microfono_inalambrico_cantidad');
        $inventario->microfonos_inalambricos_prestar = $request->input('microfono_inalambrico_activo');
        $inventario->microfonos_inalambricos_reparar = $request->input('microfono_inalambrico_inactivo');
        $inventario->parales_microfonos_cantidades = $request->input('parales_microfono_cantidad');
        $inventario->parales_microfonos_prestar = $request->input('parales_microfono_activo');
        $inventario->parales_microfonos_reparar = $request->input('parales_microfono_inactivo');
        $inventario->consola_audio_cantidades = $request->input('consola_audio_cantidad');
        $inventario->consola_audio_prestar = $request->input('consola_audio_activo');
        $inventario->consola_audio_reparar = $request->input('consola_audio_inactivo');
        $inventario->plantas_audio_cantidades = $request->input('plantas_audio_cantidad');
        $inventario->plantas_audio_prestar = $request->input('plantas_audio_activo');
        $inventario->plantas_audio_reparar = $request->input('plantas_audio_inactivo');
        $inventario->tv_plasma_cantidades = $request->input('tv_plasma_cantidad');
        $inventario->tv_plasma_prestar = $request->input('tv_plasma_activo');
        $inventario->tv_plasma_reparar = $request->input('tv_plasma_inactivo');
        $inventario->planta_electrica_cantidades = $request->input('planta_electrica_cantidad');
        $inventario->planta_electrica_prestar = $request->input('planta_electrica_activo');
        $inventario->planta_electrica_reparar = $request->input('planta_electrica_inactivo');
        $inventario->extenciones_electricas_cantidades = $request->input('extenciones_electricas_cantidad');
        $inventario->extenciones_electricas_prestar = $request->input('extenciones_electricas_activo');
        $inventario->extenciones_electricas_reparar = $request->input('extenciones_electricas_inactivo');
        $inventario->cables_microfonos_cantidades = $request->input('cables_microfono_cantidad');
        $inventario->cables_microfonos_prestar = $request->input('cables_microfono_activo');
        $inventario->cables_microfonos_reparar = $request->input('cables_microfono_inactivo');
        $inventario->video_beam_cantidades = $request->input('video_beam_cantidad');
        $inventario->video_beam_prestar = $request->input('video_beam_activo');
        $inventario->video_beam_reparar = $request->input('video_beam_inactivo');
        $inventario->almohadillas_cantidades = $request->input('almoadillas_cantidad');
        $inventario->almohadillas_prestar = $request->input('almoadillas_activo');
        $inventario->almohadillas_reparar = $request->input('almoadillas_inactivo');
        $inventario->condecoraciones_fisicas_cantidades = $request->input('condecoraciones_cantidad');
        $inventario->condecoraciones_fisicas_prestar = $request->input('condecoraciones_activo');
        $inventario->condecoraciones_fisicas_reparar = $request->input('condecoraciones_inactivo');
        $inventario->automovil_cantidades = $request->input('automoviles_cantidad');
        $inventario->automovil_prestar = $request->input('automoviles_activo');
        $inventario->automovil_reparar = $request->input('automoviles_inactivo');
        $inventario->camara_fotografica_cantidades = $request->input('camara_fotografica_cantidad');
        $inventario->camara_fotografica_prestar = $request->input('camara_fotografica_activo');
        $inventario->camara_fotografica_reparar = $request->input('camara_fotografica_inactivo');
        $inventario->camara_grabacion_cantidades = $request->input('camara_grabacion_cantidad');
        $inventario->camara_grabacion_prestar = $request->input('camara_grabacion_activo');
        $inventario->camara_grabacion_reparar = $request->input('camara_grabacion_inactivo');
        $inventario->personal_publicas_cantidades = $request->input('persoral_relaciones_publicas_cantidad');
        $inventario->personal_publicas_prestar = $request->input('persoral_relaciones_publicas_activo');
        $inventario->personal_publicas_reparar = $request->input('persoral_relaciones_publicas_inactivo');
        $inventario->carpetas_firmas_cantidades = $request->input('carpetas_membretadas_cantidad');
        $inventario->carpetas_firmas_prestar = $request->input('carpetas_membretadas_activo');
        $inventario->carpetas_firmas_reparar = $request->input('carpetas_membretadas_inactivo');
        $inventario->personal_idiomas_cantidades = $request->input('personal_idioma_cantidad');
        $inventario->personal_idiomas_prestar = $request->input('personal_idioma_activo');
        $inventario->personal_idiomas_reparar = $request->input('personal_idioma_inactivo');
        $inventario->personal_idiomas_tipo = $request->input('personal_idioma_tipo');
        $inventario->personal_sennas_cantidades = $request->input('personal_sennas_cantidad');
        $inventario->personal_sennas_prestar = $request->input('personal_sennas_activo');
        $inventario->personal_sennas_reparar = $request->input('personal_sennas_inactivo');
        $inventario->personal_culturales_prestar = $request->input('carruchas_activo');
        $inventario->personal_culturales_reparar = $request->input('personal_culturales_reparar');
        $inventario->personal_carruchas_cantidades = $request->input('carruchas_cantidad');
        $inventario->personal_carruchas_prestar = $request->input('carruchas_activo');
        $inventario->personal_carruchas_reparar = $request->input('carruchas_inactivo');
        $inventario->personal_manteleria_cantidades = $request->input('manteleria_cantidad');
        $inventario->personal_manteleria_prestar = $request->input('manteleria_activo');
        $inventario->personal_manteleria_reparar = $request->input('manteleria_inactivo');

        # Me volvi fue loco jaja XD perdon el que lea esto solo hice este sistema rapidito sin relaciones

        $inventario->save();
        return Inertia::render('Welcome');
    }
}
